
version: "3.7"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres
      ports:
        - "5432:5432"

#    environment:
#      - POSTGRES_DB=roomlayouts
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=root

